/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.medicalrecord.view.dialog;

import com.jtk.medicalrecord.entity.Pasien;
import com.jtk.medicalrecord.jpacontroller.PasienJpaController;
import com.zlib.util.ZClass;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zulkhair Abdullah D
 */
public class SearchPasienDialog extends javax.swing.JDialog {

    private final PasienJpaController pasienJpaController = new PasienJpaController();
    private List<Pasien> pasiens = new ArrayList<>();
    private final Pasien pasien;
    boolean first = true;

    /**
     * Creates new form SearchPasienDialog
     *
     * @param parent
     * @param modal
     * @param pasien
     */
    public SearchPasienDialog(java.awt.Frame parent, boolean modal, Pasien pasien) {
        super(parent, modal);
        initComponents();
        this.pasien = pasien;
        pasiens = pasienJpaController.findPasienEntities();
        createTableValue();
    }

    private void createTableValue() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Object[] columnsName = {"NIK", "Nama", "Tempat Lahir", "Tanggal Lahir", "Alamat"};

        DefaultTableModel dtm = new DefaultTableModel(null, columnsName) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (Pasien p : pasiens) {
            Object[] o = new Object[2];
            o[0] = p.getPasId();
            o[1] = p.getPasNama();
            o[2] = p.getPasTmpLhr();
            o[3] = sdf.format(p.getPasTglLhr());
            o[4] = p.getPasAlamat();

            dtm.addRow(o);
        }
        tblPasien.setModel(dtm);
    }

    private void select() {
        Pasien p = pasiens.get(tblPasien.getSelectedRow());
        ZClass.copyClass(p, pasien);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        btnPilih = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textSearch.setForeground(new java.awt.Color(153, 153, 153));
        textSearch.setText("Cari berdasarkan NIK atau Nama");
        textSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSearchFocusLost(evt);
            }
        });
        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
        });

        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIK", "Nama", "Tempat Lahir", "Tanggal Lahir", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPasien);
        if (tblPasien.getColumnModel().getColumnCount() > 0) {
            tblPasien.getColumnModel().getColumn(0).setResizable(false);
            tblPasien.getColumnModel().getColumn(1).setResizable(false);
            tblPasien.getColumnModel().getColumn(2).setResizable(false);
            tblPasien.getColumnModel().getColumn(3).setResizable(false);
            tblPasien.getColumnModel().getColumn(4).setResizable(false);
        }

        btnPilih.setText("Pilih");

        jButton1.setText("Tambah Pasien");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSearch)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilih)
                    .addComponent(jButton1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSearchFocusGained
        if (first) {
            textSearch.setForeground(Color.black);
            textSearch.setText("");
            first = false;
        }
    }//GEN-LAST:event_textSearchFocusGained

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        if (evt.getClickCount() == 2) {
            select();
        }
    }//GEN-LAST:event_tblPasienMouseClicked

    private void textSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSearchFocusLost
        if (textSearch.getText().isEmpty()) {
            textSearch.setForeground(Color.getHSBColor(153, 153, 153));
            textSearch.setText("Cari berdasarkan NIK atau Nama");
            first = true;
        }
    }//GEN-LAST:event_textSearchFocusLost

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        pasiens = pasienJpaController.findPasienByNikOrName(textSearch.getText());
        createTableValue();
    }//GEN-LAST:event_textSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inputPasienDialog dialog = new inputPasienDialog(null, true);
        dialog.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTextField textSearch;
    // End of variables declaration//GEN-END:variables
}
