/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtk.medicalrecord.view;

import com.jtk.medicalrecord.util.CardLayoutEnum;
import com.jtk.medicalrecord.util.ConfigHelper;
import com.jtk.medicalrecord.view.panel.LoginPanel;
import com.jtk.medicalrecord.view.panel.LoginPanel2;
import com.jtk.medicalrecord.view.panel.MainMenu;
import com.jtk.medicalrecord.view.panel.RegistrasiAkun;
import java.awt.CardLayout;
import javax.swing.UIManager;

/**
 *
 * @author Zulkhair Abdullah D
 */
public class MainFrame extends javax.swing.JFrame {

    public static final CardLayout cardLayout = new CardLayout();
    public static MainFrame instance;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        addCardLayout();
        setInstance();
        setLocationRelativeTo(null);
    }

    private void setInstance() {
        instance = this;
    }

    private void addCardLayout() {
        LoginPanel loginPanel = new LoginPanel();
        LoginPanel2 loginPanel2 = new LoginPanel2();
        RegistrasiAkun registrasiAkun = new RegistrasiAkun();
        MainMenu mainMenu = new MainMenu();

        cardPanel.setLayout(cardLayout);
        cardPanel.add(loginPanel, CardLayoutEnum.LOGIN.toString());
        cardPanel.add(loginPanel2, CardLayoutEnum.LOGIN2.toString());
        cardPanel.add(registrasiAkun, CardLayoutEnum.REGISTRASI_AKUN.toString());
        cardPanel.add(mainMenu, CardLayoutEnum.MAIN_MENU.toString());

        if (ConfigHelper.readConfig() == null) {
            showLoginPanel();
        } else {
            showLoginPanel2();
        }

    }

    public void showRegistrasiAkun() {
        cardLayout.show(cardPanel, CardLayoutEnum.REGISTRASI_AKUN.toString());
    }

    public void showLoginPanel() {
        cardLayout.show(cardPanel, CardLayoutEnum.LOGIN.toString());
    }

    public void showLoginPanel2() {
        cardLayout.show(cardPanel, CardLayoutEnum.LOGIN2.toString());
    }
    
    public void showMainMenu() {
        cardLayout.show(cardPanel, CardLayoutEnum.MAIN_MENU.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Medical Record");

        cardPanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        cardPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        cardPanel.setLayout(new java.awt.CardLayout());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
