/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jtk.medicalrecord.view.panel;

import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author M Haska Ash Shiddiq
 */
public class InputMedrecPemeriksaanfisik extends javax.swing.JPanel {

    /**
     * Creates new form InputMedrecPemeriksaanfisik
     */
    public InputMedrecPemeriksaanfisik() {
        initComponents();
    }
    
    public void viewState(){
        txtKesadaran.setEditable(false);
        txtLain.setEditable(false);
        txtLajuNadi.setEditable(false);
        txtLajuNafas.setEditable(false);
        txtSuhuTubuh.setEditable(false);
        txtTekananDarah.setEditable(false);
    }
    
    public void clear(){
        txtKesadaran.setText("");
        txtLain.setText("");
        txtLajuNadi.setText("");
        txtLajuNafas.setText("");
        txtSuhuTubuh.setText("");
        txtTekananDarah.setText("");
    }

    public JTextField getTxtKesadaran() {
        return txtKesadaran;
    }

    public JTextArea getTxtLain() {
        return txtLain;
    }

    public JTextField getTxtLajuNadi() {
        return txtLajuNadi;
    }

    public JTextField getTxtLajuNafas() {
        return txtLajuNafas;
    }

    public JTextField getTxtSuhuTubuh() {
        return txtSuhuTubuh;
    }

    public JTextField getTxtTekananDarah() {
        return txtTekananDarah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKesadaran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLajuNafas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSuhuTubuh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLajuNadi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTekananDarah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLain = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(240, 500));
        setPreferredSize(new java.awt.Dimension(240, 650));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pemeriksaan Fisik");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(89, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(89, 25));

        jLabel2.setText("Kesadaran");

        txtKesadaran.setPreferredSize(new java.awt.Dimension(182, 20));
        txtKesadaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKesadaranActionPerformed(evt);
            }
        });

        jLabel3.setText("Laju Nafas");

        txtLajuNafas.setPreferredSize(new java.awt.Dimension(182, 20));

        jLabel4.setText("Suhu Tubuh");

        txtSuhuTubuh.setPreferredSize(new java.awt.Dimension(182, 20));

        jLabel5.setText("Laju Nadi");

        txtLajuNadi.setPreferredSize(new java.awt.Dimension(182, 20));

        jLabel6.setText("Tekanan Darah");

        txtTekananDarah.setPreferredSize(new java.awt.Dimension(182, 20));

        jLabel7.setText("Lain - Lain");

        txtLain.setColumns(20);
        txtLain.setRows(5);
        txtLain.setMinimumSize(new java.awt.Dimension(53, 30));
        txtLain.setPreferredSize(new java.awt.Dimension(53, 30));
        jScrollPane1.setViewportView(txtLain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addComponent(txtKesadaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLajuNafas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSuhuTubuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLajuNadi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTekananDarah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKesadaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLajuNafas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSuhuTubuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLajuNadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTekananDarah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKesadaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKesadaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKesadaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtKesadaran;
    private javax.swing.JTextArea txtLain;
    private javax.swing.JTextField txtLajuNadi;
    private javax.swing.JTextField txtLajuNafas;
    private javax.swing.JTextField txtSuhuTubuh;
    private javax.swing.JTextField txtTekananDarah;
    // End of variables declaration//GEN-END:variables
}
